# Generated by Django 4.1.3 on 2023-05-09 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=128)),
                ('positionArray', models.JSONField(blank=True, null=True)),
                ('pages', models.IntegerField(null=True)),
                ('maxPageWidth', models.FloatField(default=0, null=True)),
                ('maxPageHeight', models.FloatField(default=0, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageNumber', models.IntegerField(null=True)),
                ('clipNumber', models.IntegerField(null=True)),
                ('minY', models.IntegerField(null=True)),
                ('maxY', models.IntegerField(null=True)),
                ('minX', models.IntegerField(null=True)),
                ('maxX', models.IntegerField(null=True)),
                ('note', models.CharField(blank=True, max_length=512)),
                ('fileId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='relatedFile', to='pdf_clip.file')),
            ],
        ),
    ]
