# Generated by Django 4.1.3 on 2023-02-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clipNumber', models.IntegerField()),
                ('pageNumber', models.IntegerField()),
                ('minY', models.IntegerField()),
                ('maxY', models.IntegerField()),
                ('note', models.CharField(max_length=128)),
            ],
        ),
    ]
