# Generated by Django 4.1.3 on 2023-02-11 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_clip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=128)),
                ('positionArray', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='clip',
            name='fileId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='relatedFile', to='pdf_clip.file'),
        ),
    ]
