# Generated by Django 4.1.3 on 2023-02-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_clip', '0004_alter_clip_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='pageClipNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
