# Generated by Django 4.1.3 on 2023-02-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_clip', '0005_clip_pageclipnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='maxPageHeight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='maxPageWidth',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='minPageWidth',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
