# Generated by Django 4.1.3 on 2023-02-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_clip', '0007_file_date_uploaded_file_largerpageneeded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='maxPageHeight',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='maxPageWidth',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='minPageWidth',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='positionArray',
            field=models.JSONField(blank=True),
        ),
    ]
