# Generated by Django 4.1.3 on 2023-02-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_clip', '0009_alter_file_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
