# Generated by Django 4.1.3 on 2023-02-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_clip', '0011_alter_file_largerpageneeded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='largerPageNeeded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='maxPageHeight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='maxPageWidth',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='minPageWidth',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='positionArray',
            field=models.JSONField(null=True),
        ),
    ]
