# Generated by Django 4.1.3 on 2023-02-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_clip', '0012_alter_file_largerpageneeded_alter_file_maxpageheight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='maxPageHeight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='maxPageWidth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='minPageWidth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='positionArray',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
