# Generated by Django 4.1.3 on 2023-02-21 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_clip', '0014_remove_clip_clipnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clip',
            old_name='pageClipNumber',
            new_name='clipNumber',
        ),
    ]
