# Generated by Django 4.1.3 on 2023-03-09 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_clip', '0017_clip_height_alter_clip_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='height',
        ),
    ]
