# Generated by Django 4.1.3 on 2023-03-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_clip', '0018_remove_clip_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='maxX',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clip',
            name='minX',
            field=models.IntegerField(null=True),
        ),
    ]
