# Generated by Django 4.1.3 on 2023-03-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_clip', '0019_clip_maxx_clip_minx'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='maxPageHeight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='maxPageWidth',
            field=models.FloatField(null=True),
        ),
    ]
