# Generated by Django 4.1.3 on 2023-03-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_clip', '0020_file_maxpageheight_file_maxpagewidth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='maxPageHeight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='maxPageWidth',
            field=models.FloatField(default=0),
        ),
    ]
