# Generated by Django 4.1.3 on 2023-03-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_clip', '0021_alter_file_maxpageheight_alter_file_maxpagewidth'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='pages',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
