# Generated by Django 4.1.3 on 2023-02-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_clip', '0002_file_clip_fileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='note',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
