# Generated by Django 4.1.3 on 2023-02-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_clip', '0003_alter_clip_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='note',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
    ]
