# Generated by Django 4.1.3 on 2023-02-20 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_clip', '0006_file_maxpageheight_file_maxpagewidth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='largerPageNeeded',
            field=models.BooleanField(default=False),
        ),
    ]
