# Generated by Django 4.1.3 on 2023-02-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_clip', '0008_alter_file_maxpageheight_alter_file_maxpagewidth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_uploaded',
            field=models.DateTimeField(),
        ),
    ]
