# Generated by Django 4.1.3 on 2023-02-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_clip', '0010_alter_file_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='largerPageNeeded',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
