# Generated by Django 4.1.3 on 2023-02-21 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_clip', '0013_alter_file_maxpageheight_alter_file_maxpagewidth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='clipNumber',
        ),
    ]
