# Generated by Django 4.1.3 on 2023-02-23 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_clip', '0015_rename_pageclipnumber_clip_clipnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='largerPageNeeded',
        ),
        migrations.RemoveField(
            model_name='file',
            name='maxPageHeight',
        ),
        migrations.RemoveField(
            model_name='file',
            name='maxPageWidth',
        ),
        migrations.RemoveField(
            model_name='file',
            name='minPageWidth',
        ),
    ]
