# Generated by Django 4.1.3 on 2023-03-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_clip', '0016_remove_file_largerpageneeded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clip',
            name='note',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
